apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-db
  template:
    metadata:
      labels:
        app: kanban-db
    spec:
      containers:
        - name: db
          image: nzhussup/kanban-db:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: kanban-config
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kanban-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: kanban-config
                  key: DB_NAME
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: kanban-db
