apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban-service
  template:
    metadata:
      labels:
        app: kanban-service
    spec:
      containers:
        - name: kanban-service
          image: nzhussup/kanban-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kanban-config
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kanban-secrets
                  key: DB_PASSWORD
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: kanban-config
                  key: REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: kanban-config
                  key: REDIS_PORT
            - name: SECURITY_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: kanban-secrets
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-service
spec:
  type: LoadBalancer
  ports:
    - port: 30001
      targetPort: 8080
  selector:
    app: kanban-service
